language: node_js
node_js:
- 10.16.3
cache: npm

install:
- npm install
before_script:
- chmod 0777 ./node_modules/.bin/mocha
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: QfXvA+NQ0fMr+jJ3f87hZgG+uVuFz9lv75qBfkNyS/WEKuzSHvyeB07KqbqgT2c8wIz/ai673VX42khKLT3Y8JkyN+WJHFzQuvU82a5OnssPk15bF+hOZ3p01r1OqvW4XcWwEXBaK5PV1W5i4z77klluA4NTbfwMAg298lQjYWcrf8APDr3u8kc4Bqkqy5N7w/AexW3MCYwr45tMQidazus1uaxzmrH4gpgiKWyiNZjFtiC8JomzXoyRDJ/MrRXd6oV3YxHMnzi2C6m4kADiJ+Lr4Tl5IlRfd1KsstQiiCeNI3MwWDciEWmF3FkA086fNun4gn8bAi8pFxVeEOkgj8S0FPDAX3PkP5Bg9JxEiDDsBg0GqIvcdugv2wkgOQzgHPCEwQRRL5a/PN2lq+ch04r/0vkT5qkulnIAiZV4ElJTEQnpa2+Z+B7aYoQVgEbWfWAVokf6l9lKWHEMGYiZSp1ujVXWFf2anm1V4DLRBWcf1sCH2dFwHd4CzurAy/PnqEVcWVlodeJITtm0vlQOu1zE9S46XczP+rpESyiUcke9wi30Taiq2PndTuZFLeLUSUG1Kng8K5CHgfCGCHytTNdLaGXfKRs9dzEesoplJEBRF5Kw4ktkjTPxKt4w1rpyjjpXW8VrGMa6oHsFhVVehaUw93xrbjhZUNmxgHdr00c=
  app: markdown-editor101
  on:
    repo: nikhildsahu/Markdown-Editor
notifications:
  slack:
    secure: japQ06J/hXCQIsuPkypbfvmam/Jv9ypFHMxLnVdPQWoaFMX6QcrfhJOIImkPxt1DNexVPTEUM16IjRUxHHUe38oBS9TFEQ2BVoa1hMJSj31RAagYeGmG4brhkP+b6h+54Z5/QcrxBTKbpAwQSjlWbG5eXLiH5dRABgn5OG0TyO849IVQKne0LCTsbELfyTqv7F4i/AL/L7d/OOdoWl4oa7o1zBTtrbg7s9i12UElsMkjlBP1KTW+tmLEHIEzZhm3zUWi7ZzZloglCyzWLwRCMiNjCHWtsgfaEmIXQqa3z6eO3/x+Pz3/6E/s7IqDzRmP+KQ7KLobJJZ5Pwtn9O7YOkitnOsQz/JpESCBtfdFUy5attr/MXhu7Mo7f7hfnVZhfv82uXAzgobHlDGhuwrPsE+rVR2yuNXp9x0IYXlSPDBz86mQXoEHtqTi6diXF9edihDO96/gDVoqaKwcJMq8zDddrWjGCiuNavGygwvzCIfm7F5EFL0dH5dNbMBrInb0p9wmkqWEP9rCZmzBkuIg5qfG4UodMI71SBb9w5vBoVHTCtjltsHdt7mIaYUaF9g3aJJd9M4nS9pZCNGP2a45oWWuoI6lANLg/Kar6KdB70W5abb77MHTct2xcJfcPOBDBiaq0np/f6HCYK+d4JcFmdh0vq29/nkDUUnIRQ5w1zE=
  email:
     recipients:  
    - stanleeniko@gmail.com
    - jueejain99@gmail.com
    - manasinamjoshi19@gmail.com
     on_success: always  
     on_failure: always
    